### ISSUE TITLE
Failed attempt to run the application

### ISSUE THREAD

**Issue by AliveDD** [kbrw/reaxt#19]
Hello, do you have any idea what to do about it?

```
Error: Cannot find module '/Users/me/reaxt-example/priv/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by Shakadak** [comment]
Hi, what version of reaxt is this using ? We need to do an up to date version as it is pretty old and behind by a few major versions.

**Comment by Shakadak** [comment]
I just tried building it and on recent versions of elixir the plug dependency is so old that it doesn't compile :\

**Comment by Shakadak** [comment]
I have pushed an updated version, it's not as complete as the previous version (you can check the diff of the README.md), but it runs and shows the TODO list.
```shell
cd reaxt-example
rm -rf _build deps
mix deps.get
iex -S mix
```
